export const PRODUUCT_LIST_REQUEST = "PRODUUCT_LIST_REQUEST";
export const PRODUUCT_LIST_SUCCESS = "PRODUUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUUCT_DETAILS_REQUEST = "PRODUUCT_DETAILS_REQUEST";
export const PRODUUCT_DETAILS_SUCCESS = "PRODUUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
